# Generated by Django 4.1.5 on 2023-01-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food category', 'verbose_name_plural': 'Food categories'},
        ),
        migrations.AlterModelOptions(
            name='foodobject',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
        migrations.RemoveField(
            model_name='foodobject',
            name='big_size',
        ),
    ]
