# Generated by Django 4.1.5 on 2023-01-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_foodobject_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodobject',
            name='quantity',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
