# Generated by Django 4.1.5 on 2023-01-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_foodobject_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodobject',
            name='regular_size',
            field=models.FloatField(verbose_name='Size'),
        ),
    ]
