# Generated by Django 4.1.5 on 2023-01-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_basket_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PizzaPy', max_length=64)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
