# Generated by Django 4.1.5 on 2023-01-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='working_hours',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
