# Generated by Django 4.1.5 on 2023-01-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordertakeaway_orderdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='basket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.basket'),
        ),
    ]
