# Generated by Django 4.1.5 on 2023-01-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ordertakeaway_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdelivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='ordertakeaway',
            options={'verbose_name': 'Take away', 'verbose_name_plural': 'Take away'},
        ),
    ]
