# Generated by Django 4.1.5 on 2023-01-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderdelivery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='ordertakeaway',
            name='address',
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ordertakeaway',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.restaurant'),
        ),
    ]
