# Generated by Django 4.1.5 on 2023-01-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_basket_expired_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='expired',
        ),
    ]
