# Generated by Django 4.1.5 on 2023-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderdelivery_expired_ordertakeaway_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertakeaway',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'In process'), ('3', 'Order complete')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
