# Generated by Django 4.1.5 on 2023-01-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_ordertakeaway_status_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'In process'), ('3', 'Order complete'), ('4', 'Courier picked up the order'), ('5', 'Courier delivered the order')], default='Pending', max_length=64),
        ),
    ]
