# Generated by Django 4.1.5 on 2023-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderdelivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(auto_created='Pending', choices=[('1', 'Pending'), ('2', 'In process'), ('3', 'Order complete'), ('4', 'Courier picked up the order'), ('5', 'Courier delivered the order')], max_length=64),
        ),
        migrations.AlterField(
            model_name='ordertakeaway',
            name='status',
            field=models.CharField(auto_created='Pending', choices=[('1', 'Pending'), ('2', 'In process'), ('3', 'Order complete')], max_length=20),
        ),
    ]
