# Generated by Django 4.1.5 on 2023-01-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0018_alter_orderdelivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.foodobject'),
        ),
    ]
