# Generated by Django 4.1.5 on 2023-01-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_basket_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='test',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
