# Generated by Django 4.1.5 on 2023-01-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_basket_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
    ]
