# Generated by Django 4.1.5 on 2023-01-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_basket_food_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
