# Generated by Django 4.1.5 on 2023-01-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_orderdelivery_user_alter_ordertakeaway_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='payment',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], max_length=5),
        ),
        migrations.AlterField(
            model_name='ordertakeaway',
            name='payment',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], max_length=5),
        ),
    ]
