# Generated by Django 4.1.5 on 2023-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_orderdelivery_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(auto_created=True, choices=[('Pending', 'Pending'), ('In process', 'In process'), ('Order complete, waiting for courier', 'Order complete, waiting for courier'), ('Courier picked up the order', 'Courier picked up the order'), ('Courier delivered the order', 'Courier delivered the order')], default='Pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='ordertakeaway',
            name='status',
            field=models.CharField(auto_created=True, choices=[('Pending', 'Pending'), ('In process', 'In process'), ('Order complete', 'Order complete')], default='Pending', max_length=20),
        ),
    ]
